{% set name = "httpstan" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/httpstan/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6b15a07557715e79e6fd66993930003b270f8b8b0c9e65f84978afe5e6bb3047

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: True  # [py<310]

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11 >=2.9.2
    - poetry-core >=1.0.0
    - setuptools
    - wheel
  run:
    - python
    - setuptools  >=48.0
    - aiohttp  >=3.7
    - appdirs  >=1.4
    - webargs  >=8.0
    - marshmallow  >=3.10
    - numpy  >=1.19
    - rapidjson
    - boost
    - eigen
    - tbb

test:
  imports:
    - httpstan
    - httpstan.services
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/httpstan/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: HTTP-based REST interface to Stan, a package for Bayesian inference.
  description: |
    httpstan is a shim allowing clients able to make HTTP-based requests to call functions in the Stan C++ library’s stan::services namespace. httpstan was originally developed as a “backend” for a Stan interface written in Python, PyStan.

    Stability and maintainability are two overriding goals of this software package.
  doc_url: https://httpstan.readthedocs.io/
  dev_url: https://github.com/stan-dev/httpstan

extra:
  recipe-maintainers:
    - mxr-conda
    - achangeo
    - oblute
  skip-lints:
    - python_build_tool_in_run