{% set name = "httpstan" %}
{% set version = "4.17.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/httpstan/archive/refs/tags/{{ version }}.tar.gz
  sha256: 65b580be59782bf180f38833ca950cc40cba6e410d0f73ecc9db71ca5a094a03

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
    - setuptools
  run:
    - python >=3.12,<4.0
    - setuptools >=48.0
    - aiohttp >=3.7,<4.0
    - appdirs >=1.4,<2.0
    - webargs >=8.0,<9.0
    - marshmallow >=3.10,<4.0
    - numpy >=1.19

# No such file or directory: PosixPath('$PREFIX/lib/python3.14/site-packages/httpstan/stanc')
{% set tests_to_skip = "test_compile" %}
{% set tests_to_skip = tests_to_skip + " or test_compile_syntax_error" %}
{% set tests_to_skip = tests_to_skip + " or test_compile_semantic_error" %}
{% set tests_to_skip = tests_to_skip + " or test_compile_filename" %}

{% set tests_to_skip = tests_to_skip + " or test_function_arguments" %}
{% set tests_to_skip = tests_to_skip + " or test_list_model_names" %}
{% set tests_to_skip = tests_to_skip + " or test_build_invalid_distribution" %}
{% set tests_to_skip = tests_to_skip + " or test_build_unknown_arg" %}
{% set tests_to_skip = tests_to_skip + " or test_build_integer_division_warning" %}
{% set tests_to_skip = tests_to_skip + " or test_delete_fit" %}
{% set tests_to_skip = tests_to_skip + " or test_delete_model" %}
{% set tests_to_skip = tests_to_skip + " or test_eight_schools" %}
{% set tests_to_skip = tests_to_skip + " or test_eight_schools_params" %}
{% set tests_to_skip = tests_to_skip + " or test_fits" %}
{% set tests_to_skip = tests_to_skip + " or test_models_actions_bad_args" %}
{% set tests_to_skip = tests_to_skip + " or test_fits_random_seed" %}
{% set tests_to_skip = tests_to_skip + " or test_fits_vector_sizes" %}
{% set tests_to_skip = tests_to_skip + " or test_bernoulli_fixed_param" %}
{% set tests_to_skip = tests_to_skip + " or test_generated_quantities_block" %}
{% set tests_to_skip = tests_to_skip + " or test_generated_quantities_rng" %}
{% set tests_to_skip = tests_to_skip + " or test_health_check" %}
{% set tests_to_skip = tests_to_skip + " or test_eight_schools_large" %}
{% set tests_to_skip = tests_to_skip + " or test_log_prob_analytically" %}
{% set tests_to_skip = tests_to_skip + " or test_log_prob_sampling" %}
{% set tests_to_skip = tests_to_skip + " or test_log_prob_grad_analytically" %}
{% set tests_to_skip = tests_to_skip + " or test_logger_callback" %}

{% set tests_to_skip = tests_to_skip + " or test_nan_inf" %}
{% set tests_to_skip = tests_to_skip + " or test_create_model" %}
{% set tests_to_skip = tests_to_skip + " or test_list_models" %}
{% set tests_to_skip = tests_to_skip + " or test_calculate_model_name" %}
{% set tests_to_skip = tests_to_skip + " or test_model_cache" %}
{% set tests_to_skip = tests_to_skip + " or test_sampling_initialization_failed" %}
{% set tests_to_skip = tests_to_skip + " or test_sampling_missing_data" %}
{% set tests_to_skip = tests_to_skip + " or test_transformed_data_params" %}
{% set tests_to_skip = tests_to_skip + " or test_transformed_data_rng" %}
{% set tests_to_skip = tests_to_skip + " or test_user_inits" %}
{% set tests_to_skip = tests_to_skip + " or test_user_inits_invalid_value" %}
{% set tests_to_skip = tests_to_skip + " or test_write_array" %}

# E       fixture 'unused_tcp_port' not found
{% set tests_to_skip = tests_to_skip + " or test_cvodes" %}
{% set tests_to_skip = tests_to_skip + " or test_debug_mode" %}
{% set tests_to_skip = tests_to_skip + " or test_linear_regression" %}
{% set tests_to_skip = tests_to_skip + " or test_transform_inits" %}

{% set deselected_tests = " --deselect=tests/test_bernoulli.py" %}

test:
  source_files:
    - tests
  imports:
    - httpstan
    - httpstan.services
  commands:
    - pip check
    # conftest.py used unix `fork` which is not available on Windows
    # E   ValueError: cannot find context for 'fork'
    - pytest -k "not ({{ tests_to_skip }})" {{ deselected_tests }} -vv tests  # [not win]
  requires:
    - pip
    - pytest
    - apispec
    - pyyaml

about:
  home: https://mc-stan.org
  license: ISC
  license_family: Other
  license_file: LICENSE
  summary: HTTP-based REST interface to Stan, a package for Bayesian inference.
  description: |
    httpstan is a shim allowing clients able to make HTTP-based requests to call functions in the Stan C++ library's stan::services namespace. httpstan was originally developed as a “backend” for a Stan interface written in Python, PyStan.
  doc_url: https://httpstan.readthedocs.io/
  dev_url: https://github.com/stan-dev/httpstan

extra:
  recipe-maintainers:
    - mxr-conda
    - achangeo
    - oblute
  skip-lints:
    - python_build_tools_in_host
    - avoid_noarch